src/Entity/Measurement.php
<?php

namespace App\Entity;

use App\Repository\MeasurementRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MeasurementRepository::class)]
class Measurement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'measurements')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Location $location = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: '0')]
    private ?string $max_celsius = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: '0')]
    private ?string $min_celsius = null;

    #[ORM\Column]
    private ?int $pressure_hpa = null;

    #[ORM\Column]
    private ?int $wind_speed_kmh = null;

    #[ORM\Column(length: 255)]
    private ?string $wind_direction = null;

    #[ORM\Column]
    private ?int $humidity_percent = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getMaxCelsius(): ?string
    {
        return $this->max_celsius;
    }

    public function setMaxCelsius(string $max_celsius): static
    {
        $this->max_celsius = $max_celsius;

        return $this;
    }

    public function getMinCelsius(): ?string
    {
        return $this->min_celsius;
    }

    public function setMinCelsius(string $min_celsius): static
    {
        $this->min_celsius = $min_celsius;

        return $this;
    }

    public function getPressureHpa(): ?int
    {
        return $this->pressure_hpa;
    }

    public function setPressureHpa(int $pressure_hpa): static
    {
        $this->pressure_hpa = $pressure_hpa;

        return $this;
    }

    public function getWindSpeedKmh(): ?int
    {
        return $this->wind_speed_kmh;
    }

    public function setWindSpeedKmh(int $wind_speed_kmh): static
    {
        $this->wind_speed_kmh = $wind_speed_kmh;

        return $this;
    }

    public function getWindDirection(): ?string
    {
        return $this->wind_direction;
    }

    public function setWindDirection(string $wind_direction): static
    {
        $this->wind_direction = $wind_direction;

        return $this;
    }

    public function getHumidityPercent(): ?int
    {
        return $this->humidity_percent;
    }

    public function setHumidityPercent(int $humidity_percent): static
    {
        $this->humidity_percent = $humidity_percent;

        return $this;
    }

    public function getFahrenheit(): float
    {
        $average = ($this->getMaxCelsius() + $this->getMinCelsius()) / 2;
        return ($average * 9/5) + 32;
    }
}

src/Form/MeasurementType.php
<?php

namespace App\Form;

use App\Entity\Location;
use App\Entity\Measurement;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MeasurementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date', DateType::class, [
                'widget' => 'single_text',
                'attr' => ['class' => 'datepicker'],
                'label' => 'Select date',
            ])
            ->add('max_celsius')
            ->add('min_celsius')
            ->add('pressure_hpa')
            ->add('wind_speed_kmh')
            ->add('wind_direction', ChoiceType::class, [
                'choices' => [
                    'North' => 'N',
                    'North-east' => 'NE',
                    'North-west' => 'NW',
                    'West' => 'W',
                    'South-west' => 'SW',
                    'South' => 'S',
                    'South-east' => 'SE',
                    'East' => 'E',
                ]
            ])
            ->add('humidity_percent')
            ->add('location', EntityType::class, [
                'class' => Location::class,
'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Measurement::class,
        ]);
    }
}

src/Controller/MeasurementController.php
<?php

namespace App\Controller;

use App\Entity\Measurement;
use App\Form\MeasurementType;
use App\Repository\MeasurementRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/measurement')]
class MeasurementController extends AbstractController
{
    #[Route('/', name: 'app_measurement_index', methods: ['GET'])]
    #[IsGranted('ROLE_MEASUREMENT_INDEX')]
    public function index(MeasurementRepository $measurementRepository): Response
    {
        return $this->render('measurement/index.html.twig', [
            'measurements' => $measurementRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_measurement_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_MEASUREMENT_NEW')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $measurement = new Measurement();
        $form = $this->createForm(MeasurementType::class, $measurement, [
            'validation_groups' => ['create'],
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($measurement);
            $entityManager->flush();

            return $this->redirectToRoute('app_measurement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('measurement/new.html.twig', [
            'measurement' => $measurement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_measurement_show', methods: ['GET'])]
    #[IsGranted('ROLE_MEASUREMENT_SHOW')]
    public function show(Measurement $measurement): Response
    {
        return $this->render('measurement/show.html.twig', [
            'measurement' => $measurement,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_measurement_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_MEASUREMENT_EDIT')]
    public function edit(Request $request, Measurement $measurement, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MeasurementType::class, $measurement, [
            'validation_groups' => ['edit'],
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_measurement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('measurement/edit.html.twig', [
            'measurement' => $measurement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_measurement_delete', methods: ['POST'])]
    #[IsGranted('ROLE_MEASUREMENT_DELETE')]
    public function delete(Request $request, Measurement $measurement, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$measurement->getId(), $request->request->get('_token'))) {
            $entityManager->remove($measurement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_measurement_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/measurement/_delete_form.html.twig
<form method="post" action="{{ path('app_measurement_delete', {'id': measurement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ measurement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/measurement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/measurement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Measurement{% endblock %}

{% block body %}
    <h1>Edit Measurement</h1>

    {{ include('measurement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_measurement_index') }}">back to list</a>

    {{ include('measurement/_delete_form.html.twig') }}
{% endblock %}

templates/measurement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Measurement index{% endblock %}

{% block body %}
    <h1>Measurements</h1>

    <div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>City</th>
                <th>Max temperature (&deg;C)</th>
                <th>Min temperature (&deg;C)</th>
                <th>Pressure (hPa)</th>
                <th>Wind speed (km/h)</th>
                <th>Wind direction</th>
                <th>Humidity %</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for measurement in measurements %}
            <tr>
                <td>{{ measurement.id }}</td>
                <td>{{ measurement.date ? measurement.date|date('Y-m-d') : '' }}</td>
                <td>{{ measurement.location.city }}</td>
                <td>{{ measurement.maxCelsius }}</td>
                <td>{{ measurement.minCelsius }}</td>
                <td>{{ measurement.pressureHpa }}</td>
                <td>{{ measurement.windSpeedKmh }}</td>
                <td>{{ measurement.windDirection }}</td>
                <td>{{ measurement.humidityPercent }}</td>
                <td>
                    {% if is_granted('ROLE_MEASUREMENT_SHOW') %}
                        <a href="{{ path('app_measurement_show', {'id': measurement.id}) }}">show</a>
                    {% endif %}
                    {% if is_granted('ROLE_MEASUREMENT_EDIT') %}
                        <a href="{{ path('app_measurement_edit', {'id': measurement.id}) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>

    {% if is_granted('ROLE_MEASUREMENT_NEW') %}
        <a href="{{ path('app_measurement_new') }}">Create new</a>
    {% endif %}
{% endblock %}

templates/measurement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Measurement{% endblock %}

{% block body %}
    <h1>Create new Measurement</h1>

    {{ include('measurement/_form.html.twig') }}

    <a href="{{ path('app_measurement_index') }}">back to list</a>
{% endblock %}

templates/measurement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Measurement{% endblock %}

{% block body %}
    <h1>Measurement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ measurement.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ measurement.date ? measurement.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ measurement.location.city }}</td>
            </tr>
            <tr>
                <th>Max_celsius</th>
                <td>{{ measurement.maxCelsius }}</td>
            </tr>
            <tr>
                <th>Min_celsius</th>
                <td>{{ measurement.minCelsius }}</td>
            </tr>
            <tr>
                <th>Pressure_hpa</th>
                <td>{{ measurement.pressureHpa }}</td>
            </tr>
            <tr>
                <th>Wind_speed_kmh</th>
                <td>{{ measurement.windSpeedKmh }}</td>
            </tr>
            <tr>
                <th>Wind_direction</th>
                <td>{{ measurement.windDirection }}</td>
            </tr>
            <tr>
                <th>Humidity_percent</th>
                <td>{{ measurement.humidityPercent }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_measurement_index') }}">back to list</a>

    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('app_measurement_edit', {'id': measurement.id}) }}">edit</a>

        {{ include('measurement/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}